# Generated by Django 3.1.7 on 2021-03-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_number',
            field=models.CharField(max_length=10),
        ),
    ]
