# Generated by Django 3.1.7 on 2021-03-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20210306_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bool',
            new_name='isStudent',
        ),
    ]
