# Generated by Django 3.1.7 on 2021-03-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20210306_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.profile'),
        ),
        migrations.AlterField(
            model_name='submitedexercise',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.profile'),
        ),
        migrations.AlterField(
            model_name='video',
            name='professor_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.profile'),
        ),
    ]
