# Generated by Django 3.1.7 on 2021-03-06 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20210306_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitedexercise',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='submitedExerciseFiles/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercisefile',
            field=models.FileField(upload_to='exerciseFiles/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
