# Generated by Django 3.1.7 on 2021-03-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20210306_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_number',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
