# Generated by Django 3.1.7 on 2021-03-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exersizename', models.CharField(max_length=200)),
                ('date', models.DateTimeField(editable=False)),
                ('detai', models.CharField(max_length=1000)),
                ('exercisefile', models.CharField(max_length=1000)),
            ],
        ),
    ]
